services:
  rhyno_gym:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rhyno_gym_automation
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - ./data:/app/data
      - ./temp:/app/temp
    environment:
      - NODE_ENV=production
      - PORT=3001
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"